"""add unique constraint to folders

Revision ID: 01dd30d6b8c5
Revises: 9d1de9e640a1
Create Date: 2026-07-30 10:51:21.186453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01dd30d6b8c5'
down_revision: Union[str, Sequence[str], None] = '9d1de9e640a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_owner_parent_name', 'folders', ['owner_id', 'parent_folder_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_owner_parent_name', 'folders', type_='unique')
    # ### end Alembic commands ###
