"""updated the permission to include specific values

Revision ID: 404013644d43
Revises: 01dd30d6b8c5
Create Date: 2026-07-30 11:00:04.304379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '404013644d43'
down_revision: Union[str, Sequence[str], None] = '01dd30d6b8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    permission_role = postgresql.ENUM(
        'viewer',
        'editor',
        'owner',
        name='permission_role'
    )

    permission_role.create(op.get_bind())

    op.alter_column('permissions', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('viewer', 'editor', 'owner', name='permission_role'),postgresql_using="role::permission_role",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'permissions',
        'role',
        existing_type=postgresql.ENUM(
            'viewer',
            'editor',
            'owner',
            name='permission_role'
        ),
        type_=sa.VARCHAR(),
        postgresql_using="role::text",
        existing_nullable=False
    )

    permission_role = postgresql.ENUM(
        'viewer',
        'editor',
        'owner',
        name='permission_role'
    )

    permission_role.drop(op.get_bind())
    # ### end Alembic commands ###
